<?php
/**
 * MembershipTypeResourceApi
 * PHP version 5
 *
 * @category Class
 * @package  Idealogic\MembershipAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Application API
 *
 * API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Idealogic\MembershipAPI\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Idealogic\MembershipAPI\ApiException;
use Idealogic\MembershipAPI\Configuration;
use Idealogic\MembershipAPI\HeaderSelector;
use Idealogic\MembershipAPI\ObjectSerializer;

/**
 * MembershipTypeResourceApi Class Doc Comment
 *
 * @category Class
 * @package  Idealogic\MembershipAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MembershipTypeResourceApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation countMembershipTypesUsingGET
     *
     * countMembershipTypes
     *
     * @param  int $id_equals id_equals (optional)
     * @param  int $id_greater_than id_greater_than (optional)
     * @param  int $id_greater_than_or_equal id_greater_than_or_equal (optional)
     * @param  int[] $id_in id_in (optional)
     * @param  int $id_less_than id_less_than (optional)
     * @param  int $id_less_than_or_equal id_less_than_or_equal (optional)
     * @param  int $id_not_equals id_not_equals (optional)
     * @param  bool $id_specified id_specified (optional)
     * @param  string $name_contains name_contains (optional)
     * @param  string $name_does_not_contain name_does_not_contain (optional)
     * @param  string $name_equals name_equals (optional)
     * @param  string[] $name_in name_in (optional)
     * @param  string $name_not_equals name_not_equals (optional)
     * @param  bool $name_specified name_specified (optional)
     * @param  int $number_type_id_equals number_type_id_equals (optional)
     * @param  int $number_type_id_greater_than number_type_id_greater_than (optional)
     * @param  int $number_type_id_greater_than_or_equal number_type_id_greater_than_or_equal (optional)
     * @param  int[] $number_type_id_in number_type_id_in (optional)
     * @param  int $number_type_id_less_than number_type_id_less_than (optional)
     * @param  int $number_type_id_less_than_or_equal number_type_id_less_than_or_equal (optional)
     * @param  int $number_type_id_not_equals number_type_id_not_equals (optional)
     * @param  bool $number_type_id_specified number_type_id_specified (optional)
     * @param  int $organisation_id organisation_id (optional)
     *
     * @throws \Idealogic\MembershipAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return int
     */
    public function countMembershipTypesUsingGET($id_equals = null, $id_greater_than = null, $id_greater_than_or_equal = null, $id_in = null, $id_less_than = null, $id_less_than_or_equal = null, $id_not_equals = null, $id_specified = null, $name_contains = null, $name_does_not_contain = null, $name_equals = null, $name_in = null, $name_not_equals = null, $name_specified = null, $number_type_id_equals = null, $number_type_id_greater_than = null, $number_type_id_greater_than_or_equal = null, $number_type_id_in = null, $number_type_id_less_than = null, $number_type_id_less_than_or_equal = null, $number_type_id_not_equals = null, $number_type_id_specified = null, $organisation_id = null)
    {
        list($response) = $this->countMembershipTypesUsingGETWithHttpInfo($id_equals, $id_greater_than, $id_greater_than_or_equal, $id_in, $id_less_than, $id_less_than_or_equal, $id_not_equals, $id_specified, $name_contains, $name_does_not_contain, $name_equals, $name_in, $name_not_equals, $name_specified, $number_type_id_equals, $number_type_id_greater_than, $number_type_id_greater_than_or_equal, $number_type_id_in, $number_type_id_less_than, $number_type_id_less_than_or_equal, $number_type_id_not_equals, $number_type_id_specified, $organisation_id);
        return $response;
    }

    /**
     * Operation countMembershipTypesUsingGETWithHttpInfo
     *
     * countMembershipTypes
     *
     * @param  int $id_equals (optional)
     * @param  int $id_greater_than (optional)
     * @param  int $id_greater_than_or_equal (optional)
     * @param  int[] $id_in (optional)
     * @param  int $id_less_than (optional)
     * @param  int $id_less_than_or_equal (optional)
     * @param  int $id_not_equals (optional)
     * @param  bool $id_specified (optional)
     * @param  string $name_contains (optional)
     * @param  string $name_does_not_contain (optional)
     * @param  string $name_equals (optional)
     * @param  string[] $name_in (optional)
     * @param  string $name_not_equals (optional)
     * @param  bool $name_specified (optional)
     * @param  int $number_type_id_equals (optional)
     * @param  int $number_type_id_greater_than (optional)
     * @param  int $number_type_id_greater_than_or_equal (optional)
     * @param  int[] $number_type_id_in (optional)
     * @param  int $number_type_id_less_than (optional)
     * @param  int $number_type_id_less_than_or_equal (optional)
     * @param  int $number_type_id_not_equals (optional)
     * @param  bool $number_type_id_specified (optional)
     * @param  int $organisation_id (optional)
     *
     * @throws \Idealogic\MembershipAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of int, HTTP status code, HTTP response headers (array of strings)
     */
    public function countMembershipTypesUsingGETWithHttpInfo($id_equals = null, $id_greater_than = null, $id_greater_than_or_equal = null, $id_in = null, $id_less_than = null, $id_less_than_or_equal = null, $id_not_equals = null, $id_specified = null, $name_contains = null, $name_does_not_contain = null, $name_equals = null, $name_in = null, $name_not_equals = null, $name_specified = null, $number_type_id_equals = null, $number_type_id_greater_than = null, $number_type_id_greater_than_or_equal = null, $number_type_id_in = null, $number_type_id_less_than = null, $number_type_id_less_than_or_equal = null, $number_type_id_not_equals = null, $number_type_id_specified = null, $organisation_id = null)
    {
        $returnType = 'int';
        $request = $this->countMembershipTypesUsingGETRequest($id_equals, $id_greater_than, $id_greater_than_or_equal, $id_in, $id_less_than, $id_less_than_or_equal, $id_not_equals, $id_specified, $name_contains, $name_does_not_contain, $name_equals, $name_in, $name_not_equals, $name_specified, $number_type_id_equals, $number_type_id_greater_than, $number_type_id_greater_than_or_equal, $number_type_id_in, $number_type_id_less_than, $number_type_id_less_than_or_equal, $number_type_id_not_equals, $number_type_id_specified, $organisation_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'int',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation countMembershipTypesUsingGETAsync
     *
     * countMembershipTypes
     *
     * @param  int $id_equals (optional)
     * @param  int $id_greater_than (optional)
     * @param  int $id_greater_than_or_equal (optional)
     * @param  int[] $id_in (optional)
     * @param  int $id_less_than (optional)
     * @param  int $id_less_than_or_equal (optional)
     * @param  int $id_not_equals (optional)
     * @param  bool $id_specified (optional)
     * @param  string $name_contains (optional)
     * @param  string $name_does_not_contain (optional)
     * @param  string $name_equals (optional)
     * @param  string[] $name_in (optional)
     * @param  string $name_not_equals (optional)
     * @param  bool $name_specified (optional)
     * @param  int $number_type_id_equals (optional)
     * @param  int $number_type_id_greater_than (optional)
     * @param  int $number_type_id_greater_than_or_equal (optional)
     * @param  int[] $number_type_id_in (optional)
     * @param  int $number_type_id_less_than (optional)
     * @param  int $number_type_id_less_than_or_equal (optional)
     * @param  int $number_type_id_not_equals (optional)
     * @param  bool $number_type_id_specified (optional)
     * @param  int $organisation_id (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function countMembershipTypesUsingGETAsync($id_equals = null, $id_greater_than = null, $id_greater_than_or_equal = null, $id_in = null, $id_less_than = null, $id_less_than_or_equal = null, $id_not_equals = null, $id_specified = null, $name_contains = null, $name_does_not_contain = null, $name_equals = null, $name_in = null, $name_not_equals = null, $name_specified = null, $number_type_id_equals = null, $number_type_id_greater_than = null, $number_type_id_greater_than_or_equal = null, $number_type_id_in = null, $number_type_id_less_than = null, $number_type_id_less_than_or_equal = null, $number_type_id_not_equals = null, $number_type_id_specified = null, $organisation_id = null)
    {
        return $this->countMembershipTypesUsingGETAsyncWithHttpInfo($id_equals, $id_greater_than, $id_greater_than_or_equal, $id_in, $id_less_than, $id_less_than_or_equal, $id_not_equals, $id_specified, $name_contains, $name_does_not_contain, $name_equals, $name_in, $name_not_equals, $name_specified, $number_type_id_equals, $number_type_id_greater_than, $number_type_id_greater_than_or_equal, $number_type_id_in, $number_type_id_less_than, $number_type_id_less_than_or_equal, $number_type_id_not_equals, $number_type_id_specified, $organisation_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation countMembershipTypesUsingGETAsyncWithHttpInfo
     *
     * countMembershipTypes
     *
     * @param  int $id_equals (optional)
     * @param  int $id_greater_than (optional)
     * @param  int $id_greater_than_or_equal (optional)
     * @param  int[] $id_in (optional)
     * @param  int $id_less_than (optional)
     * @param  int $id_less_than_or_equal (optional)
     * @param  int $id_not_equals (optional)
     * @param  bool $id_specified (optional)
     * @param  string $name_contains (optional)
     * @param  string $name_does_not_contain (optional)
     * @param  string $name_equals (optional)
     * @param  string[] $name_in (optional)
     * @param  string $name_not_equals (optional)
     * @param  bool $name_specified (optional)
     * @param  int $number_type_id_equals (optional)
     * @param  int $number_type_id_greater_than (optional)
     * @param  int $number_type_id_greater_than_or_equal (optional)
     * @param  int[] $number_type_id_in (optional)
     * @param  int $number_type_id_less_than (optional)
     * @param  int $number_type_id_less_than_or_equal (optional)
     * @param  int $number_type_id_not_equals (optional)
     * @param  bool $number_type_id_specified (optional)
     * @param  int $organisation_id (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function countMembershipTypesUsingGETAsyncWithHttpInfo($id_equals = null, $id_greater_than = null, $id_greater_than_or_equal = null, $id_in = null, $id_less_than = null, $id_less_than_or_equal = null, $id_not_equals = null, $id_specified = null, $name_contains = null, $name_does_not_contain = null, $name_equals = null, $name_in = null, $name_not_equals = null, $name_specified = null, $number_type_id_equals = null, $number_type_id_greater_than = null, $number_type_id_greater_than_or_equal = null, $number_type_id_in = null, $number_type_id_less_than = null, $number_type_id_less_than_or_equal = null, $number_type_id_not_equals = null, $number_type_id_specified = null, $organisation_id = null)
    {
        $returnType = 'int';
        $request = $this->countMembershipTypesUsingGETRequest($id_equals, $id_greater_than, $id_greater_than_or_equal, $id_in, $id_less_than, $id_less_than_or_equal, $id_not_equals, $id_specified, $name_contains, $name_does_not_contain, $name_equals, $name_in, $name_not_equals, $name_specified, $number_type_id_equals, $number_type_id_greater_than, $number_type_id_greater_than_or_equal, $number_type_id_in, $number_type_id_less_than, $number_type_id_less_than_or_equal, $number_type_id_not_equals, $number_type_id_specified, $organisation_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'countMembershipTypesUsingGET'
     *
     * @param  int $id_equals (optional)
     * @param  int $id_greater_than (optional)
     * @param  int $id_greater_than_or_equal (optional)
     * @param  int[] $id_in (optional)
     * @param  int $id_less_than (optional)
     * @param  int $id_less_than_or_equal (optional)
     * @param  int $id_not_equals (optional)
     * @param  bool $id_specified (optional)
     * @param  string $name_contains (optional)
     * @param  string $name_does_not_contain (optional)
     * @param  string $name_equals (optional)
     * @param  string[] $name_in (optional)
     * @param  string $name_not_equals (optional)
     * @param  bool $name_specified (optional)
     * @param  int $number_type_id_equals (optional)
     * @param  int $number_type_id_greater_than (optional)
     * @param  int $number_type_id_greater_than_or_equal (optional)
     * @param  int[] $number_type_id_in (optional)
     * @param  int $number_type_id_less_than (optional)
     * @param  int $number_type_id_less_than_or_equal (optional)
     * @param  int $number_type_id_not_equals (optional)
     * @param  bool $number_type_id_specified (optional)
     * @param  int $organisation_id (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function countMembershipTypesUsingGETRequest($id_equals = null, $id_greater_than = null, $id_greater_than_or_equal = null, $id_in = null, $id_less_than = null, $id_less_than_or_equal = null, $id_not_equals = null, $id_specified = null, $name_contains = null, $name_does_not_contain = null, $name_equals = null, $name_in = null, $name_not_equals = null, $name_specified = null, $number_type_id_equals = null, $number_type_id_greater_than = null, $number_type_id_greater_than_or_equal = null, $number_type_id_in = null, $number_type_id_less_than = null, $number_type_id_less_than_or_equal = null, $number_type_id_not_equals = null, $number_type_id_specified = null, $organisation_id = null)
    {

        $resourcePath = '/api/membership-types/count';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($id_equals !== null) {
            $queryParams['id.equals'] = ObjectSerializer::toQueryValue($id_equals);
        }
        // query params
        if ($id_greater_than !== null) {
            $queryParams['id.greaterThan'] = ObjectSerializer::toQueryValue($id_greater_than);
        }
        // query params
        if ($id_greater_than_or_equal !== null) {
            $queryParams['id.greaterThanOrEqual'] = ObjectSerializer::toQueryValue($id_greater_than_or_equal);
        }
        // query params
        if (is_array($id_in)) {
            $queryParams['id.in'] = $id_in;
        } else
        if ($id_in !== null) {
            $queryParams['id.in'] = ObjectSerializer::toQueryValue($id_in);
        }
        // query params
        if ($id_less_than !== null) {
            $queryParams['id.lessThan'] = ObjectSerializer::toQueryValue($id_less_than);
        }
        // query params
        if ($id_less_than_or_equal !== null) {
            $queryParams['id.lessThanOrEqual'] = ObjectSerializer::toQueryValue($id_less_than_or_equal);
        }
        // query params
        if ($id_not_equals !== null) {
            $queryParams['id.notEquals'] = ObjectSerializer::toQueryValue($id_not_equals);
        }
        // query params
        if ($id_specified !== null) {
            $queryParams['id.specified'] = ObjectSerializer::toQueryValue($id_specified);
        }
        // query params
        if ($name_contains !== null) {
            $queryParams['name.contains'] = ObjectSerializer::toQueryValue($name_contains);
        }
        // query params
        if ($name_does_not_contain !== null) {
            $queryParams['name.doesNotContain'] = ObjectSerializer::toQueryValue($name_does_not_contain);
        }
        // query params
        if ($name_equals !== null) {
            $queryParams['name.equals'] = ObjectSerializer::toQueryValue($name_equals);
        }
        // query params
        if (is_array($name_in)) {
            $queryParams['name.in'] = $name_in;
        } else
        if ($name_in !== null) {
            $queryParams['name.in'] = ObjectSerializer::toQueryValue($name_in);
        }
        // query params
        if ($name_not_equals !== null) {
            $queryParams['name.notEquals'] = ObjectSerializer::toQueryValue($name_not_equals);
        }
        // query params
        if ($name_specified !== null) {
            $queryParams['name.specified'] = ObjectSerializer::toQueryValue($name_specified);
        }
        // query params
        if ($number_type_id_equals !== null) {
            $queryParams['numberTypeId.equals'] = ObjectSerializer::toQueryValue($number_type_id_equals);
        }
        // query params
        if ($number_type_id_greater_than !== null) {
            $queryParams['numberTypeId.greaterThan'] = ObjectSerializer::toQueryValue($number_type_id_greater_than);
        }
        // query params
        if ($number_type_id_greater_than_or_equal !== null) {
            $queryParams['numberTypeId.greaterThanOrEqual'] = ObjectSerializer::toQueryValue($number_type_id_greater_than_or_equal);
        }
        // query params
        if (is_array($number_type_id_in)) {
            $queryParams['numberTypeId.in'] = $number_type_id_in;
        } else
        if ($number_type_id_in !== null) {
            $queryParams['numberTypeId.in'] = ObjectSerializer::toQueryValue($number_type_id_in);
        }
        // query params
        if ($number_type_id_less_than !== null) {
            $queryParams['numberTypeId.lessThan'] = ObjectSerializer::toQueryValue($number_type_id_less_than);
        }
        // query params
        if ($number_type_id_less_than_or_equal !== null) {
            $queryParams['numberTypeId.lessThanOrEqual'] = ObjectSerializer::toQueryValue($number_type_id_less_than_or_equal);
        }
        // query params
        if ($number_type_id_not_equals !== null) {
            $queryParams['numberTypeId.notEquals'] = ObjectSerializer::toQueryValue($number_type_id_not_equals);
        }
        // query params
        if ($number_type_id_specified !== null) {
            $queryParams['numberTypeId.specified'] = ObjectSerializer::toQueryValue($number_type_id_specified);
        }
        // query params
        if ($organisation_id !== null) {
            $queryParams['organisationId'] = ObjectSerializer::toQueryValue($organisation_id);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['*/*']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['*/*'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation createMembershipTypeUsingPOST
     *
     * createMembershipType
     *
     * @param  \Idealogic\MembershipAPI\Model\MembershipTypeDTO $membership_type_dto membershipTypeDTO (required)
     *
     * @throws \Idealogic\MembershipAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Idealogic\MembershipAPI\Model\MembershipTypeDTO
     */
    public function createMembershipTypeUsingPOST($membership_type_dto)
    {
        list($response) = $this->createMembershipTypeUsingPOSTWithHttpInfo($membership_type_dto);
        return $response;
    }

    /**
     * Operation createMembershipTypeUsingPOSTWithHttpInfo
     *
     * createMembershipType
     *
     * @param  \Idealogic\MembershipAPI\Model\MembershipTypeDTO $membership_type_dto membershipTypeDTO (required)
     *
     * @throws \Idealogic\MembershipAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Idealogic\MembershipAPI\Model\MembershipTypeDTO, HTTP status code, HTTP response headers (array of strings)
     */
    public function createMembershipTypeUsingPOSTWithHttpInfo($membership_type_dto)
    {
        $returnType = '\Idealogic\MembershipAPI\Model\MembershipTypeDTO';
        $request = $this->createMembershipTypeUsingPOSTRequest($membership_type_dto);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Idealogic\MembershipAPI\Model\MembershipTypeDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createMembershipTypeUsingPOSTAsync
     *
     * createMembershipType
     *
     * @param  \Idealogic\MembershipAPI\Model\MembershipTypeDTO $membership_type_dto membershipTypeDTO (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createMembershipTypeUsingPOSTAsync($membership_type_dto)
    {
        return $this->createMembershipTypeUsingPOSTAsyncWithHttpInfo($membership_type_dto)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createMembershipTypeUsingPOSTAsyncWithHttpInfo
     *
     * createMembershipType
     *
     * @param  \Idealogic\MembershipAPI\Model\MembershipTypeDTO $membership_type_dto membershipTypeDTO (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createMembershipTypeUsingPOSTAsyncWithHttpInfo($membership_type_dto)
    {
        $returnType = '\Idealogic\MembershipAPI\Model\MembershipTypeDTO';
        $request = $this->createMembershipTypeUsingPOSTRequest($membership_type_dto);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createMembershipTypeUsingPOST'
     *
     * @param  \Idealogic\MembershipAPI\Model\MembershipTypeDTO $membership_type_dto membershipTypeDTO (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function createMembershipTypeUsingPOSTRequest($membership_type_dto)
    {
        // verify the required parameter 'membership_type_dto' is set
        if ($membership_type_dto === null || (is_array($membership_type_dto) && count($membership_type_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $membership_type_dto when calling createMembershipTypeUsingPOST'
            );
        }

        $resourcePath = '/api/membership-types';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($membership_type_dto)) {
            $_tempBody = $membership_type_dto;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['*/*']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['*/*'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteMembershipTypeUsingDELETE
     *
     * deleteMembershipType
     *
     * @param  int $id id (required)
     *
     * @throws \Idealogic\MembershipAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteMembershipTypeUsingDELETE($id)
    {
        $this->deleteMembershipTypeUsingDELETEWithHttpInfo($id);
    }

    /**
     * Operation deleteMembershipTypeUsingDELETEWithHttpInfo
     *
     * deleteMembershipType
     *
     * @param  int $id id (required)
     *
     * @throws \Idealogic\MembershipAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteMembershipTypeUsingDELETEWithHttpInfo($id)
    {
        $returnType = '';
        $request = $this->deleteMembershipTypeUsingDELETERequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation deleteMembershipTypeUsingDELETEAsync
     *
     * deleteMembershipType
     *
     * @param  int $id id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteMembershipTypeUsingDELETEAsync($id)
    {
        return $this->deleteMembershipTypeUsingDELETEAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteMembershipTypeUsingDELETEAsyncWithHttpInfo
     *
     * deleteMembershipType
     *
     * @param  int $id id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteMembershipTypeUsingDELETEAsyncWithHttpInfo($id)
    {
        $returnType = '';
        $request = $this->deleteMembershipTypeUsingDELETERequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteMembershipTypeUsingDELETE'
     *
     * @param  int $id id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function deleteMembershipTypeUsingDELETERequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling deleteMembershipTypeUsingDELETE'
            );
        }

        $resourcePath = '/api/membership-types/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['*/*']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['*/*'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAllMembershipTypesUsingGET
     *
     * getAllMembershipTypes
     *
     * @param  int $id_equals id_equals (optional)
     * @param  int $id_greater_than id_greater_than (optional)
     * @param  int $id_greater_than_or_equal id_greater_than_or_equal (optional)
     * @param  int[] $id_in id_in (optional)
     * @param  int $id_less_than id_less_than (optional)
     * @param  int $id_less_than_or_equal id_less_than_or_equal (optional)
     * @param  int $id_not_equals id_not_equals (optional)
     * @param  bool $id_specified id_specified (optional)
     * @param  string $name_contains name_contains (optional)
     * @param  string $name_does_not_contain name_does_not_contain (optional)
     * @param  string $name_equals name_equals (optional)
     * @param  string[] $name_in name_in (optional)
     * @param  string $name_not_equals name_not_equals (optional)
     * @param  bool $name_specified name_specified (optional)
     * @param  int $number_type_id_equals number_type_id_equals (optional)
     * @param  int $number_type_id_greater_than number_type_id_greater_than (optional)
     * @param  int $number_type_id_greater_than_or_equal number_type_id_greater_than_or_equal (optional)
     * @param  int[] $number_type_id_in number_type_id_in (optional)
     * @param  int $number_type_id_less_than number_type_id_less_than (optional)
     * @param  int $number_type_id_less_than_or_equal number_type_id_less_than_or_equal (optional)
     * @param  int $number_type_id_not_equals number_type_id_not_equals (optional)
     * @param  bool $number_type_id_specified number_type_id_specified (optional)
     * @param  int $organisation_id organisation_id (optional)
     * @param  int $page Page number of the requested page (optional)
     * @param  int $size Size of a page (optional)
     * @param  string[] $sort Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported. (optional)
     *
     * @throws \Idealogic\MembershipAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Idealogic\MembershipAPI\Model\MembershipTypeDTO[]
     */
    public function getAllMembershipTypesUsingGET($id_equals = null, $id_greater_than = null, $id_greater_than_or_equal = null, $id_in = null, $id_less_than = null, $id_less_than_or_equal = null, $id_not_equals = null, $id_specified = null, $name_contains = null, $name_does_not_contain = null, $name_equals = null, $name_in = null, $name_not_equals = null, $name_specified = null, $number_type_id_equals = null, $number_type_id_greater_than = null, $number_type_id_greater_than_or_equal = null, $number_type_id_in = null, $number_type_id_less_than = null, $number_type_id_less_than_or_equal = null, $number_type_id_not_equals = null, $number_type_id_specified = null, $organisation_id = null, $page = null, $size = null, $sort = null)
    {
        list($response) = $this->getAllMembershipTypesUsingGETWithHttpInfo($id_equals, $id_greater_than, $id_greater_than_or_equal, $id_in, $id_less_than, $id_less_than_or_equal, $id_not_equals, $id_specified, $name_contains, $name_does_not_contain, $name_equals, $name_in, $name_not_equals, $name_specified, $number_type_id_equals, $number_type_id_greater_than, $number_type_id_greater_than_or_equal, $number_type_id_in, $number_type_id_less_than, $number_type_id_less_than_or_equal, $number_type_id_not_equals, $number_type_id_specified, $organisation_id, $page, $size, $sort);
        return $response;
    }

    /**
     * Operation getAllMembershipTypesUsingGETWithHttpInfo
     *
     * getAllMembershipTypes
     *
     * @param  int $id_equals (optional)
     * @param  int $id_greater_than (optional)
     * @param  int $id_greater_than_or_equal (optional)
     * @param  int[] $id_in (optional)
     * @param  int $id_less_than (optional)
     * @param  int $id_less_than_or_equal (optional)
     * @param  int $id_not_equals (optional)
     * @param  bool $id_specified (optional)
     * @param  string $name_contains (optional)
     * @param  string $name_does_not_contain (optional)
     * @param  string $name_equals (optional)
     * @param  string[] $name_in (optional)
     * @param  string $name_not_equals (optional)
     * @param  bool $name_specified (optional)
     * @param  int $number_type_id_equals (optional)
     * @param  int $number_type_id_greater_than (optional)
     * @param  int $number_type_id_greater_than_or_equal (optional)
     * @param  int[] $number_type_id_in (optional)
     * @param  int $number_type_id_less_than (optional)
     * @param  int $number_type_id_less_than_or_equal (optional)
     * @param  int $number_type_id_not_equals (optional)
     * @param  bool $number_type_id_specified (optional)
     * @param  int $organisation_id (optional)
     * @param  int $page Page number of the requested page (optional)
     * @param  int $size Size of a page (optional)
     * @param  string[] $sort Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported. (optional)
     *
     * @throws \Idealogic\MembershipAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Idealogic\MembershipAPI\Model\MembershipTypeDTO[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllMembershipTypesUsingGETWithHttpInfo($id_equals = null, $id_greater_than = null, $id_greater_than_or_equal = null, $id_in = null, $id_less_than = null, $id_less_than_or_equal = null, $id_not_equals = null, $id_specified = null, $name_contains = null, $name_does_not_contain = null, $name_equals = null, $name_in = null, $name_not_equals = null, $name_specified = null, $number_type_id_equals = null, $number_type_id_greater_than = null, $number_type_id_greater_than_or_equal = null, $number_type_id_in = null, $number_type_id_less_than = null, $number_type_id_less_than_or_equal = null, $number_type_id_not_equals = null, $number_type_id_specified = null, $organisation_id = null, $page = null, $size = null, $sort = null)
    {
        $returnType = '\Idealogic\MembershipAPI\Model\MembershipTypeDTO[]';
        $request = $this->getAllMembershipTypesUsingGETRequest($id_equals, $id_greater_than, $id_greater_than_or_equal, $id_in, $id_less_than, $id_less_than_or_equal, $id_not_equals, $id_specified, $name_contains, $name_does_not_contain, $name_equals, $name_in, $name_not_equals, $name_specified, $number_type_id_equals, $number_type_id_greater_than, $number_type_id_greater_than_or_equal, $number_type_id_in, $number_type_id_less_than, $number_type_id_less_than_or_equal, $number_type_id_not_equals, $number_type_id_specified, $organisation_id, $page, $size, $sort);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Idealogic\MembershipAPI\Model\MembershipTypeDTO[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAllMembershipTypesUsingGETAsync
     *
     * getAllMembershipTypes
     *
     * @param  int $id_equals (optional)
     * @param  int $id_greater_than (optional)
     * @param  int $id_greater_than_or_equal (optional)
     * @param  int[] $id_in (optional)
     * @param  int $id_less_than (optional)
     * @param  int $id_less_than_or_equal (optional)
     * @param  int $id_not_equals (optional)
     * @param  bool $id_specified (optional)
     * @param  string $name_contains (optional)
     * @param  string $name_does_not_contain (optional)
     * @param  string $name_equals (optional)
     * @param  string[] $name_in (optional)
     * @param  string $name_not_equals (optional)
     * @param  bool $name_specified (optional)
     * @param  int $number_type_id_equals (optional)
     * @param  int $number_type_id_greater_than (optional)
     * @param  int $number_type_id_greater_than_or_equal (optional)
     * @param  int[] $number_type_id_in (optional)
     * @param  int $number_type_id_less_than (optional)
     * @param  int $number_type_id_less_than_or_equal (optional)
     * @param  int $number_type_id_not_equals (optional)
     * @param  bool $number_type_id_specified (optional)
     * @param  int $organisation_id (optional)
     * @param  int $page Page number of the requested page (optional)
     * @param  int $size Size of a page (optional)
     * @param  string[] $sort Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllMembershipTypesUsingGETAsync($id_equals = null, $id_greater_than = null, $id_greater_than_or_equal = null, $id_in = null, $id_less_than = null, $id_less_than_or_equal = null, $id_not_equals = null, $id_specified = null, $name_contains = null, $name_does_not_contain = null, $name_equals = null, $name_in = null, $name_not_equals = null, $name_specified = null, $number_type_id_equals = null, $number_type_id_greater_than = null, $number_type_id_greater_than_or_equal = null, $number_type_id_in = null, $number_type_id_less_than = null, $number_type_id_less_than_or_equal = null, $number_type_id_not_equals = null, $number_type_id_specified = null, $organisation_id = null, $page = null, $size = null, $sort = null)
    {
        return $this->getAllMembershipTypesUsingGETAsyncWithHttpInfo($id_equals, $id_greater_than, $id_greater_than_or_equal, $id_in, $id_less_than, $id_less_than_or_equal, $id_not_equals, $id_specified, $name_contains, $name_does_not_contain, $name_equals, $name_in, $name_not_equals, $name_specified, $number_type_id_equals, $number_type_id_greater_than, $number_type_id_greater_than_or_equal, $number_type_id_in, $number_type_id_less_than, $number_type_id_less_than_or_equal, $number_type_id_not_equals, $number_type_id_specified, $organisation_id, $page, $size, $sort)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllMembershipTypesUsingGETAsyncWithHttpInfo
     *
     * getAllMembershipTypes
     *
     * @param  int $id_equals (optional)
     * @param  int $id_greater_than (optional)
     * @param  int $id_greater_than_or_equal (optional)
     * @param  int[] $id_in (optional)
     * @param  int $id_less_than (optional)
     * @param  int $id_less_than_or_equal (optional)
     * @param  int $id_not_equals (optional)
     * @param  bool $id_specified (optional)
     * @param  string $name_contains (optional)
     * @param  string $name_does_not_contain (optional)
     * @param  string $name_equals (optional)
     * @param  string[] $name_in (optional)
     * @param  string $name_not_equals (optional)
     * @param  bool $name_specified (optional)
     * @param  int $number_type_id_equals (optional)
     * @param  int $number_type_id_greater_than (optional)
     * @param  int $number_type_id_greater_than_or_equal (optional)
     * @param  int[] $number_type_id_in (optional)
     * @param  int $number_type_id_less_than (optional)
     * @param  int $number_type_id_less_than_or_equal (optional)
     * @param  int $number_type_id_not_equals (optional)
     * @param  bool $number_type_id_specified (optional)
     * @param  int $organisation_id (optional)
     * @param  int $page Page number of the requested page (optional)
     * @param  int $size Size of a page (optional)
     * @param  string[] $sort Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllMembershipTypesUsingGETAsyncWithHttpInfo($id_equals = null, $id_greater_than = null, $id_greater_than_or_equal = null, $id_in = null, $id_less_than = null, $id_less_than_or_equal = null, $id_not_equals = null, $id_specified = null, $name_contains = null, $name_does_not_contain = null, $name_equals = null, $name_in = null, $name_not_equals = null, $name_specified = null, $number_type_id_equals = null, $number_type_id_greater_than = null, $number_type_id_greater_than_or_equal = null, $number_type_id_in = null, $number_type_id_less_than = null, $number_type_id_less_than_or_equal = null, $number_type_id_not_equals = null, $number_type_id_specified = null, $organisation_id = null, $page = null, $size = null, $sort = null)
    {
        $returnType = '\Idealogic\MembershipAPI\Model\MembershipTypeDTO[]';
        $request = $this->getAllMembershipTypesUsingGETRequest($id_equals, $id_greater_than, $id_greater_than_or_equal, $id_in, $id_less_than, $id_less_than_or_equal, $id_not_equals, $id_specified, $name_contains, $name_does_not_contain, $name_equals, $name_in, $name_not_equals, $name_specified, $number_type_id_equals, $number_type_id_greater_than, $number_type_id_greater_than_or_equal, $number_type_id_in, $number_type_id_less_than, $number_type_id_less_than_or_equal, $number_type_id_not_equals, $number_type_id_specified, $organisation_id, $page, $size, $sort);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllMembershipTypesUsingGET'
     *
     * @param  int $id_equals (optional)
     * @param  int $id_greater_than (optional)
     * @param  int $id_greater_than_or_equal (optional)
     * @param  int[] $id_in (optional)
     * @param  int $id_less_than (optional)
     * @param  int $id_less_than_or_equal (optional)
     * @param  int $id_not_equals (optional)
     * @param  bool $id_specified (optional)
     * @param  string $name_contains (optional)
     * @param  string $name_does_not_contain (optional)
     * @param  string $name_equals (optional)
     * @param  string[] $name_in (optional)
     * @param  string $name_not_equals (optional)
     * @param  bool $name_specified (optional)
     * @param  int $number_type_id_equals (optional)
     * @param  int $number_type_id_greater_than (optional)
     * @param  int $number_type_id_greater_than_or_equal (optional)
     * @param  int[] $number_type_id_in (optional)
     * @param  int $number_type_id_less_than (optional)
     * @param  int $number_type_id_less_than_or_equal (optional)
     * @param  int $number_type_id_not_equals (optional)
     * @param  bool $number_type_id_specified (optional)
     * @param  int $organisation_id (optional)
     * @param  int $page Page number of the requested page (optional)
     * @param  int $size Size of a page (optional)
     * @param  string[] $sort Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getAllMembershipTypesUsingGETRequest($id_equals = null, $id_greater_than = null, $id_greater_than_or_equal = null, $id_in = null, $id_less_than = null, $id_less_than_or_equal = null, $id_not_equals = null, $id_specified = null, $name_contains = null, $name_does_not_contain = null, $name_equals = null, $name_in = null, $name_not_equals = null, $name_specified = null, $number_type_id_equals = null, $number_type_id_greater_than = null, $number_type_id_greater_than_or_equal = null, $number_type_id_in = null, $number_type_id_less_than = null, $number_type_id_less_than_or_equal = null, $number_type_id_not_equals = null, $number_type_id_specified = null, $organisation_id = null, $page = null, $size = null, $sort = null)
    {

        $resourcePath = '/api/membership-types';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($id_equals !== null) {
            $queryParams['id.equals'] = ObjectSerializer::toQueryValue($id_equals);
        }
        // query params
        if ($id_greater_than !== null) {
            $queryParams['id.greaterThan'] = ObjectSerializer::toQueryValue($id_greater_than);
        }
        // query params
        if ($id_greater_than_or_equal !== null) {
            $queryParams['id.greaterThanOrEqual'] = ObjectSerializer::toQueryValue($id_greater_than_or_equal);
        }
        // query params
        if (is_array($id_in)) {
            $queryParams['id.in'] = $id_in;
        } else
        if ($id_in !== null) {
            $queryParams['id.in'] = ObjectSerializer::toQueryValue($id_in);
        }
        // query params
        if ($id_less_than !== null) {
            $queryParams['id.lessThan'] = ObjectSerializer::toQueryValue($id_less_than);
        }
        // query params
        if ($id_less_than_or_equal !== null) {
            $queryParams['id.lessThanOrEqual'] = ObjectSerializer::toQueryValue($id_less_than_or_equal);
        }
        // query params
        if ($id_not_equals !== null) {
            $queryParams['id.notEquals'] = ObjectSerializer::toQueryValue($id_not_equals);
        }
        // query params
        if ($id_specified !== null) {
            $queryParams['id.specified'] = ObjectSerializer::toQueryValue($id_specified);
        }
        // query params
        if ($name_contains !== null) {
            $queryParams['name.contains'] = ObjectSerializer::toQueryValue($name_contains);
        }
        // query params
        if ($name_does_not_contain !== null) {
            $queryParams['name.doesNotContain'] = ObjectSerializer::toQueryValue($name_does_not_contain);
        }
        // query params
        if ($name_equals !== null) {
            $queryParams['name.equals'] = ObjectSerializer::toQueryValue($name_equals);
        }
        // query params
        if (is_array($name_in)) {
            $queryParams['name.in'] = $name_in;
        } else
        if ($name_in !== null) {
            $queryParams['name.in'] = ObjectSerializer::toQueryValue($name_in);
        }
        // query params
        if ($name_not_equals !== null) {
            $queryParams['name.notEquals'] = ObjectSerializer::toQueryValue($name_not_equals);
        }
        // query params
        if ($name_specified !== null) {
            $queryParams['name.specified'] = ObjectSerializer::toQueryValue($name_specified);
        }
        // query params
        if ($number_type_id_equals !== null) {
            $queryParams['numberTypeId.equals'] = ObjectSerializer::toQueryValue($number_type_id_equals);
        }
        // query params
        if ($number_type_id_greater_than !== null) {
            $queryParams['numberTypeId.greaterThan'] = ObjectSerializer::toQueryValue($number_type_id_greater_than);
        }
        // query params
        if ($number_type_id_greater_than_or_equal !== null) {
            $queryParams['numberTypeId.greaterThanOrEqual'] = ObjectSerializer::toQueryValue($number_type_id_greater_than_or_equal);
        }
        // query params
        if (is_array($number_type_id_in)) {
            $queryParams['numberTypeId.in'] = $number_type_id_in;
        } else
        if ($number_type_id_in !== null) {
            $queryParams['numberTypeId.in'] = ObjectSerializer::toQueryValue($number_type_id_in);
        }
        // query params
        if ($number_type_id_less_than !== null) {
            $queryParams['numberTypeId.lessThan'] = ObjectSerializer::toQueryValue($number_type_id_less_than);
        }
        // query params
        if ($number_type_id_less_than_or_equal !== null) {
            $queryParams['numberTypeId.lessThanOrEqual'] = ObjectSerializer::toQueryValue($number_type_id_less_than_or_equal);
        }
        // query params
        if ($number_type_id_not_equals !== null) {
            $queryParams['numberTypeId.notEquals'] = ObjectSerializer::toQueryValue($number_type_id_not_equals);
        }
        // query params
        if ($number_type_id_specified !== null) {
            $queryParams['numberTypeId.specified'] = ObjectSerializer::toQueryValue($number_type_id_specified);
        }
        // query params
        if ($organisation_id !== null) {
            $queryParams['organisationId'] = ObjectSerializer::toQueryValue($organisation_id);
        }
        // query params
        if ($page !== null) {
            $queryParams['page'] = ObjectSerializer::toQueryValue($page);
        }
        // query params
        if ($size !== null) {
            $queryParams['size'] = ObjectSerializer::toQueryValue($size);
        }
        // query params
        if (is_array($sort)) {
            $queryParams['sort'] = $sort;
        } else
        if ($sort !== null) {
            $queryParams['sort'] = ObjectSerializer::toQueryValue($sort);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['*/*']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['*/*'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getMembershipTypeUsingGET
     *
     * getMembershipType
     *
     * @param  int $id id (required)
     *
     * @throws \Idealogic\MembershipAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Idealogic\MembershipAPI\Model\MembershipTypeDTO
     */
    public function getMembershipTypeUsingGET($id)
    {
        list($response) = $this->getMembershipTypeUsingGETWithHttpInfo($id);
        return $response;
    }

    /**
     * Operation getMembershipTypeUsingGETWithHttpInfo
     *
     * getMembershipType
     *
     * @param  int $id id (required)
     *
     * @throws \Idealogic\MembershipAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Idealogic\MembershipAPI\Model\MembershipTypeDTO, HTTP status code, HTTP response headers (array of strings)
     */
    public function getMembershipTypeUsingGETWithHttpInfo($id)
    {
        $returnType = '\Idealogic\MembershipAPI\Model\MembershipTypeDTO';
        $request = $this->getMembershipTypeUsingGETRequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Idealogic\MembershipAPI\Model\MembershipTypeDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getMembershipTypeUsingGETAsync
     *
     * getMembershipType
     *
     * @param  int $id id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMembershipTypeUsingGETAsync($id)
    {
        return $this->getMembershipTypeUsingGETAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getMembershipTypeUsingGETAsyncWithHttpInfo
     *
     * getMembershipType
     *
     * @param  int $id id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMembershipTypeUsingGETAsyncWithHttpInfo($id)
    {
        $returnType = '\Idealogic\MembershipAPI\Model\MembershipTypeDTO';
        $request = $this->getMembershipTypeUsingGETRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getMembershipTypeUsingGET'
     *
     * @param  int $id id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getMembershipTypeUsingGETRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getMembershipTypeUsingGET'
            );
        }

        $resourcePath = '/api/membership-types/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['*/*']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['*/*'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateMembershipTypeUsingPUT
     *
     * updateMembershipType
     *
     * @param  \Idealogic\MembershipAPI\Model\MembershipTypeDTO $membership_type_dto membershipTypeDTO (required)
     *
     * @throws \Idealogic\MembershipAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Idealogic\MembershipAPI\Model\MembershipTypeDTO
     */
    public function updateMembershipTypeUsingPUT($membership_type_dto)
    {
        list($response) = $this->updateMembershipTypeUsingPUTWithHttpInfo($membership_type_dto);
        return $response;
    }

    /**
     * Operation updateMembershipTypeUsingPUTWithHttpInfo
     *
     * updateMembershipType
     *
     * @param  \Idealogic\MembershipAPI\Model\MembershipTypeDTO $membership_type_dto membershipTypeDTO (required)
     *
     * @throws \Idealogic\MembershipAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Idealogic\MembershipAPI\Model\MembershipTypeDTO, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateMembershipTypeUsingPUTWithHttpInfo($membership_type_dto)
    {
        $returnType = '\Idealogic\MembershipAPI\Model\MembershipTypeDTO';
        $request = $this->updateMembershipTypeUsingPUTRequest($membership_type_dto);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Idealogic\MembershipAPI\Model\MembershipTypeDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateMembershipTypeUsingPUTAsync
     *
     * updateMembershipType
     *
     * @param  \Idealogic\MembershipAPI\Model\MembershipTypeDTO $membership_type_dto membershipTypeDTO (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateMembershipTypeUsingPUTAsync($membership_type_dto)
    {
        return $this->updateMembershipTypeUsingPUTAsyncWithHttpInfo($membership_type_dto)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateMembershipTypeUsingPUTAsyncWithHttpInfo
     *
     * updateMembershipType
     *
     * @param  \Idealogic\MembershipAPI\Model\MembershipTypeDTO $membership_type_dto membershipTypeDTO (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateMembershipTypeUsingPUTAsyncWithHttpInfo($membership_type_dto)
    {
        $returnType = '\Idealogic\MembershipAPI\Model\MembershipTypeDTO';
        $request = $this->updateMembershipTypeUsingPUTRequest($membership_type_dto);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateMembershipTypeUsingPUT'
     *
     * @param  \Idealogic\MembershipAPI\Model\MembershipTypeDTO $membership_type_dto membershipTypeDTO (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function updateMembershipTypeUsingPUTRequest($membership_type_dto)
    {
        // verify the required parameter 'membership_type_dto' is set
        if ($membership_type_dto === null || (is_array($membership_type_dto) && count($membership_type_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $membership_type_dto when calling updateMembershipTypeUsingPUT'
            );
        }

        $resourcePath = '/api/membership-types';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($membership_type_dto)) {
            $_tempBody = $membership_type_dto;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['*/*']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['*/*'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
