<?php
/**
 * LatestPeriodMembershipStatusResponseDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  Idealogic\MembershipAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Application API
 *
 * API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Idealogic\MembershipAPI\Model;

use \ArrayAccess;
use \Idealogic\MembershipAPI\ObjectSerializer;

/**
 * LatestPeriodMembershipStatusResponseDTO Class Doc Comment
 *
 * @category Class
 * @package  Idealogic\MembershipAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LatestPeriodMembershipStatusResponseDTO implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'LatestPeriodMembershipStatusResponseDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'main_member_id' => 'int',
        'membership_period_id' => 'int',
        'membership_period_name' => 'string',
        'membership_type_name' => 'string',
        'status' => '\Idealogic\MembershipAPI\Model\MembershipStatusDTO[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'main_member_id' => 'int64',
        'membership_period_id' => 'int64',
        'membership_period_name' => null,
        'membership_type_name' => null,
        'status' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'main_member_id' => 'mainMemberId',
        'membership_period_id' => 'membershipPeriodId',
        'membership_period_name' => 'membershipPeriodName',
        'membership_type_name' => 'membershipTypeName',
        'status' => 'status'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'main_member_id' => 'setMainMemberId',
        'membership_period_id' => 'setMembershipPeriodId',
        'membership_period_name' => 'setMembershipPeriodName',
        'membership_type_name' => 'setMembershipTypeName',
        'status' => 'setStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'main_member_id' => 'getMainMemberId',
        'membership_period_id' => 'getMembershipPeriodId',
        'membership_period_name' => 'getMembershipPeriodName',
        'membership_type_name' => 'getMembershipTypeName',
        'status' => 'getStatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['main_member_id'] = isset($data['main_member_id']) ? $data['main_member_id'] : null;
        $this->container['membership_period_id'] = isset($data['membership_period_id']) ? $data['membership_period_id'] : null;
        $this->container['membership_period_name'] = isset($data['membership_period_name']) ? $data['membership_period_name'] : null;
        $this->container['membership_type_name'] = isset($data['membership_type_name']) ? $data['membership_type_name'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets main_member_id
     *
     * @return int
     */
    public function getMainMemberId()
    {
        return $this->container['main_member_id'];
    }

    /**
     * Sets main_member_id
     *
     * @param int $main_member_id main_member_id
     *
     * @return $this
     */
    public function setMainMemberId($main_member_id)
    {
        $this->container['main_member_id'] = $main_member_id;

        return $this;
    }

    /**
     * Gets membership_period_id
     *
     * @return int
     */
    public function getMembershipPeriodId()
    {
        return $this->container['membership_period_id'];
    }

    /**
     * Sets membership_period_id
     *
     * @param int $membership_period_id membership_period_id
     *
     * @return $this
     */
    public function setMembershipPeriodId($membership_period_id)
    {
        $this->container['membership_period_id'] = $membership_period_id;

        return $this;
    }

    /**
     * Gets membership_period_name
     *
     * @return string
     */
    public function getMembershipPeriodName()
    {
        return $this->container['membership_period_name'];
    }

    /**
     * Sets membership_period_name
     *
     * @param string $membership_period_name membership_period_name
     *
     * @return $this
     */
    public function setMembershipPeriodName($membership_period_name)
    {
        $this->container['membership_period_name'] = $membership_period_name;

        return $this;
    }

    /**
     * Gets membership_type_name
     *
     * @return string
     */
    public function getMembershipTypeName()
    {
        return $this->container['membership_type_name'];
    }

    /**
     * Sets membership_type_name
     *
     * @param string $membership_type_name membership_type_name
     *
     * @return $this
     */
    public function setMembershipTypeName($membership_type_name)
    {
        $this->container['membership_type_name'] = $membership_type_name;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Idealogic\MembershipAPI\Model\MembershipStatusDTO[]
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Idealogic\MembershipAPI\Model\MembershipStatusDTO[] $status status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


